### ISSUE TITLE
`make build` bails out on PostCSS

### ISSUE THREAD

**Issue by amotl** [crate/crate-docs-theme#307]
Hi there,

when aiming to release version 0.18.0, `make build` croaked like
```
    ./node_modules/css-loader/dist/cjs.js!./src/crate/theme/rtd/crate/static/css/index.css 39 bytes [not cacheable] [built] [code generated] [1 error]

ERROR in ./src/crate/theme/rtd/crate/static/css/index.css (./node_modules/css-loader/dist/cjs.js!./src/crate/theme/rtd/crate/static/css/index.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/amo/dev/crate/docs/crate-docs-theme/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:416:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:669:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (/Users/amo/dev/crate/docs/crate-docs-theme/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/amo/dev/crate/docs/crate-docs-theme/node_modules/css-loader/dist/index.js:12:39)
```

With kind regards,
Andreas.

**Comment by amotl** [comment]
Apparently, it is related to Node.js 17, which happens to be the default on my machine.

- https://github.com/facebook/create-react-app/issues/11565
- https://stackoverflow.com/questions/69693907/error-err-package-path-not-exported-package-subpath-lib-tokenize-is-not-d

Let's use Node.js 14 LTS instead.
